---
- name: Hyper-V Cluster Health Check Report
  hosts: all
  gather_facts: false
  tasks:
    - name: Create temp file
      win_tempfile:
        state: file
        suffix: html
      register: tempfile_1

    - name: Run PowerShell Script
      script: ClusterHealthCheck.ps1 -htmlfile {{ tempfile_1.path }}

    - name: Fetch output from Cluster
      #fetch:
      #  src: "{{ tempfile_1.path }}"
      #  dest: /tmp/logs
      slurp:
        src: "{{ tempfile_1.path }}"
      register: slurped_data
      #register: htmlfile

    - name: Decode data
      set_fact:
        data: "{{ slurped_data['content'] | b64decode(encoding=utf-16-le) }}"
#      delegate_to: localhost

#    - name: read file
#      shell: cat "{{ htmlfile.dest }}"
#      register: htmlcontent
#      delegate_to: localhost

    #- name: Send mail
    #  mail:
    #    host: mail.winadmin.org
    #    port: 587
    #    username: admin@winadmin.org
    #    password: creMa6u7!
    #    to: vg@live.in
    #    from: admin@winadmin.org
    #    subject: Hyper-V CLuster Health Check Report
    #    subtype: html
    #    body: "{{ htmlcontent }}"
    #  delegate_to: localhost