---
- name: Hyper-V Cluster Health Check Report
  hosts: all
  gather_facts: false
  tasks:
    - name: Create temp file
      win_tempfile:
        state: file
        suffix: .html
      register: tempfile_1

    - name: Create temp file 2
      win_tempfile:
        state: file
        suffix: body
      register: tempfile_2

    - name: Run PowerShell Script
      script: ClusterHealthCheck.ps1 -htmlfile {{ tempfile_1.path }} -mailbody {{ tempfile_2.path }}

    - name: Fetch output from Cluster
      fetch:
        src: "{{ tempfile_1.path }}"
        dest: /tmp/logs
      register: htmlfile

    - name: Fetch mail_body
      slurp:
        src: "{{ tempfile_2.path }}"
      register: data2

    - name: Send mail
      mail:
        host: dc01.winadmin.local
        port: 465
        username: wintel@winadmin.local
        password: P@ssw0rd
        to: venu@winadmin.local
        from: wintel@winadmin.local
        subject: Hyper-V CLuster Health Check Report
        subtype: html
        body: "{{ data2['content'] | b64decode(encoding='utf-16') }}"
        attach: "{{ htmlfile.dest }}"
      delegate_to: localhost
      