---
- name: Hyper-V Cluster Health Check Report
  hosts: all
  gather_facts: false
  tasks:
    - name: Create temp file
      win_tempfile:
        state: file
        suffix: html
      register: tempfile_1

    - name: Create temp file 2
      win_tempfile:
        state: file
        suffix: body
      register: tempfile_2

    - name: Run PowerShell Script
      script: ClusterHealthCheck.ps1 -htmlfile {{ tempfile_1.path }} -mailbody {{ tempfile_2.path }}

    - name: Fetch output from Cluster
      fetch:
        src: "{{ tempfile_1.path }}"
        dest: /tmp/logs
      #slurp:
      #  src: "{{ tempfile_1.path }}"
      #register: data1
      register: htmlfile

    #- name: Decode data
    #  set_fact:
    #    data1: "{{ data1['content'] | b64decode(encoding='utf-16') }}"
    #  delegate_to: localhost

    - name: Fetch mail_body
      slurp:
        src: "{{ tempfile_2.path }}"
      register: data2

    - name: Decode data
      set_fact:
        data2: "{{ data2['content'] | b64decode(encoding='utf-16') }}"
      delegate_to: localhost

#    - name: read file
#      shell: cat "{{ htmlfile.dest }}"
#      register: htmlcontent
#      delegate_to: localhost

    - name: Send mail
      mail:
        host: dc01.winadmin.local
        port: 465
        username: wintel@winadmin.local
        password: P@ssw0rd
        to: venu@winadmin.local
        from: wintel@winadmin.local
        subject: Hyper-V CLuster Health Check Report
        subtype: html
        body: "{{ data2 }}"
        attach: "{{ htmlfile.dest }}"
      delegate_to: localhost
      